# Source-pinned RAD engines remain separate executables because their globals,
# BSP structures and floating-point conventions are not interchangeable.
function(lm_replace before after)
    string(FIND "${code}" "${before}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Upstream hook not found in ${family}/${relative}: ${before}")
    endif()
    string(REPLACE "${before}" "${after}" code "${code}")
    set(code "${code}" PARENT_SCOPE)
endfunction()

foreach(family zhlt vhlt sdhlt)
    set(upstream "${DEPS}/compiler-sources/${family}")
    set(rad hlrad)
    if(family STREQUAL sdhlt)
        set(upstream "${upstream}/src/sdhlt")
        set(rad sdHLRAD)
        set(commit df45198b3c03a5a09e9d1aead9c9457e51753e39)
    elseif(family STREQUAL vhlt)
        set(commit 13b83f91d093ef146a9a78834578994d85f99d96)
    else()
        set(commit da4f9d76cf425b06864c29b32dab73892e36a6c6)
    endif()
    if(NOT EXISTS "${upstream}/${rad}/qrad.cpp")
        message(FATAL_ERROR "Missing ${family} sources. Configure the project again to restore dependencies")
    endif()
    set(common blockmem bspfile cmdlib filelib log mathlib messages scriplib threads winding)
    set(engine lerp lightmap mathutil nomatrix qrad qradutil sparse trace transfers transparency vismatrix vismatrixutil)
    if(family STREQUAL zhlt)
        list(APPEND common resourcelock)
    else()
        list(APPEND common cmdlinecfg)
        list(APPEND engine compress loadtextures)
    endif()
    if(family STREQUAL sdhlt)
        list(APPEND engine meshdesc meshtrace progmesh stringlib studio)
    endif()
    set(files)
    foreach(file IN LISTS common)
        list(APPEND files common/${file}.cpp)
    endforeach()
    foreach(file IN LISTS engine)
        list(APPEND files ${rad}/${file}.cpp)
    endforeach()
    file(GLOB headers RELATIVE "${upstream}" "${upstream}/common/*.h" "${upstream}/template/*.h" "${upstream}/${rad}/*.h")
    list(APPEND files ${headers})
    set(sources)
    set(generated "${CMAKE_BINARY_DIR}/compiler-sources/${family}")
    foreach(relative IN LISTS files)
        file(READ "${upstream}/${relative}" code)
        string(REPLACE "\r\n" "\n" code "${code}")
        if(relative STREQUAL "${rad}/qrad.cpp")
            lm_replace("int             main(const int argc, char** argv)" "int native_rad_main(const int argc, char** argv)")
            lm_replace("    char global_lights[_MAX_PATH];" "    ReadLightFile(user_rad);\n    ReadInfoTexlights();\n    return;\n    char global_lights[_MAX_PATH];")
            lm_replace("LoadBSPFile(g_source);" "LoadBSPFile(getenv(\"LM_BSP_INPUT\"));\n    lm_native_loaded();")
            lm_replace("WriteBSPFile(g_source);" "lm_native_finish();")
            lm_replace("    RadWorld();" "    lm_mark(LM_GEOMETRY);\n    RadWorld();")
            lm_replace("    CreateDirectLights();" "    lm_mark(LM_DIRECT);\n    CreateDirectLights();")
            lm_replace("    DeleteDirectLights();" "    lm_native_structure();\n    DeleteDirectLights();")
            lm_replace("        MakeScalesStub();" "        lm_mark(LM_TRANSFERS);\n        MakeScalesStub();")
            lm_replace("        BounceLight();" "        lm_mark(LM_BOUNCE);\n        BounceLight();")
            lm_replace("    FreeTransfers();" "    lm_mark(LM_ENCODE);\n    FreeTransfers();")
            if(NOT family STREQUAL zhlt)
                lm_replace("ParseParamFile (argcold, argvold, argc, argv);" "argc = argcold; argv = argvold; /* Explicit runner arguments only. */")
                lm_replace("\tReduceLightmap();" "\tlm_native_capture();\n\tReduceLightmap();")
            endif()
            if(family STREQUAL sdhlt)
                # SDHLT renamed this function to include texture minimum light.
                string(REPLACE "ReadInfoTexlights();\n    return;" "ReadInfoTexAndMinlights();\n    return;" code "${code}")
            endif()
            set(code "// RadBruter transport/timing hooks, September 2026. Upstream lighting is unchanged.\n#include \"runtime.h\"\n#include \"compiler.h\"\n${code}")
        elseif(relative STREQUAL "${rad}/lightmap.cpp")
            lm_replace("\tif (!(tex->flags & TEX_SPECIAL))"
                "\tlm_original_grid(l->surfnum, l->texmins, l->texsize);\n\tif (!(tex->flags & TEX_SPECIAL))")
            lm_replace("\t        lb[0] *= g_colour_lightscale[0];" "            lm_native_sample(facenum, k, j, fl->numsamples, lb, minlight);\n\t        lb[0] *= g_colour_lightscale[0];")
            if(family STREQUAL zhlt)
                lm_replace("    hlassume(numdlights, assume_NoLights);" "    /* Zero-light probes are intentional in the inverse solver. */")
            endif()
            set(code "// RadBruter raw-sample observation hook, September 2026.\n#include \"runtime.h\"\n#include \"compiler.h\"\n${code}")
        elseif(relative STREQUAL "${rad}/loadtextures.cpp")
            # Missing reflectivity must not silently turn into a gray texture.
            lm_replace("Warning (\"Texture '%s': texture is not found in wad files.\", tex->name);"
                "Error (\"Texture '%s' is missing; supply its WAD directory with --waddir.\", tex->name);")
        endif()
        if(family STREQUAL zhlt)
            string(REPLACE "strcpy_s(" "strcpy(" code "${code}")
            string(REPLACE "sprintf_s(" "sprintf(" code "${code}")
            string(REPLACE "sscanf_s(" "sscanf(" code "${code}")
            string(REPLACE "_strlwr(" "strlwr(" code "${code}")
            foreach(function strdup open read close unlink)
                string(REPLACE "_${function}(" "${function}(" code "${code}")
            endforeach()
            string(REPLACE "q_entry((int)pParam);" "q_entry(int(reinterpret_cast<intptr_t>(pParam)));" code "${code}")
            string(REPLACE "ThreadEntryStub, (void*)i" "ThreadEntryStub, reinterpret_cast<void*>(intptr_t(i))" code "${code}")
            string(REPLACE "(int)tnodes" "(uintptr_t)tnodes" code "${code}")
            if(relative STREQUAL "common/threads.cpp")
                set(code "#include <cstdint>\n${code}")
            endif()
            if(relative STREQUAL "common/cmdlib.cpp")
                set(code "#include <algorithm>\nusing std::max;\n${code}")
            endif()
            if(relative STREQUAL "${rad}/mathutil.cpp")
                string(REPLACE "inline " "" code "${code}")
                string(REPLACE "INLINE " "" code "${code}")
            endif()
        endif()
        if(WIN32 AND relative STREQUAL "common/filelib.cpp")
            set(code "#include \"platform_io.h\"\n#define fopen lm_fopen\n${code}")
        endif()
        if(WIN32 AND relative STREQUAL "common/win32fix.h")
            string(REPLACE "#define vsnprintf _vsnprintf" "/* The UCRT supplies vsnprintf. */" code "${code}")
            string(REPLACE "#define snprintf  _snprintf" "/* The UCRT supplies snprintf. */" code "${code}")
        endif()
        if(WIN32)
            string(REGEX REPLACE "__asm[ \t\n]*\\{[ \t\n]*int 3;?[ \t\n]*\\}" "__debugbreak();" code "${code}")
        endif()
        if(relative STREQUAL "common/threads.cpp")
            string(REPLACE "q_entry((int)pParam);" "q_entry(int(reinterpret_cast<intptr_t>(pParam)));" code "${code}")
            string(REPLACE "(LPVOID) i," "reinterpret_cast<LPVOID>(intptr_t(i))," code "${code}")
        endif()
        if(family STREQUAL sdhlt AND relative STREQUAL "${rad}/meshtrace.h")
            string(REPLACE "((t *)((byte *)l - (int)(long int)&(((t *)0)->m)))"
                "reinterpret_cast<t *>(reinterpret_cast<byte *>(l) - offsetof(t, m))" code "${code}")
        endif()
        if(family STREQUAL sdhlt AND relative STREQUAL "${rad}/stringlib.cpp")
            string(REPLACE "register " "" code "${code}")
        endif()
        if(NOT family STREQUAL zhlt AND relative STREQUAL "common/winding.cpp")
            lm_replace("Winding::Winding(UINT32 numpoints)\n{\n    hlassert(numpoints >= 3);"
                "Winding::Winding(UINT32 numpoints)\n{\n    // Clipping a sample fragment can produce an empty winding.\n    hlassert(numpoints == 0 || numpoints >= 3);")
        endif()
        if(NOT family STREQUAL zhlt AND relative STREQUAL "common/bspfile.cpp")
            lm_replace("void GetFaceExtents (int facenum, int mins_out[2], int maxs_out[2])\n{"
                "void GetFaceExtents (int facenum, int mins_out[2], int maxs_out[2])\n{\n    int original_size[2];\n    if (lm_original_grid(facenum, mins_out, original_size)) {\n        maxs_out[0] = mins_out[0] + original_size[0];\n        maxs_out[1] = mins_out[1] + original_size[1];\n        return;\n    }")
            set(code "#include \"runtime.h\"\n${code}")
        endif()
        set(code "// Modified for RadBruter native transport and Linux/64-bit portability, September 2026.\n${code}")
        set(previous "")
        if(EXISTS "${generated}/${relative}")
            file(READ "${generated}/${relative}" previous)
        endif()
        if(NOT previous STREQUAL code)
            file(WRITE "${generated}/${relative}" "${code}")
        endif()
        if(relative MATCHES "\\.cpp$")
            list(APPEND sources "${generated}/${relative}")
        endif()
    endforeach()
    add_executable(radbruter-${family} ${sources} "${CMAKE_SOURCE_DIR}/src/compiler.cpp")
    set_target_properties(radbruter-${family} PROPERTIES CXX_STANDARD 17
        RUNTIME_OUTPUT_DIRECTORY "${RB_OUTPUT_DIR}/compilers")
    target_include_directories(radbruter-${family} PRIVATE "${generated}/common" "${generated}/template" "${generated}/${rad}" "${CMAKE_SOURCE_DIR}/src")
    string(TOUPPER "${family}" upper_family)
    target_compile_definitions(radbruter-${family} PRIVATE LM_NATIVE_WORKER LM_${upper_family}
        LM_COMPILER_NAME="${family}" LM_COMPILER_COMMIT="${commit}"
        NDEBUG STDC_HEADERS SIZEOF_CHARP=8)
    if(WIN32)
        target_compile_definitions(radbruter-${family} PRIVATE SYSTEM_WIN32 VERSION_64BIT)
    else()
        target_compile_definitions(radbruter-${family} PRIVATE VERSION_LINUX SYSTEM_POSIX STDC_HEADERS
            HAVE_FCNTL_H HAVE_PTHREAD_H HAVE_STDDEF_H HAVE_SYS_RESOURCE_H HAVE_SYS_STAT_H
            HAVE_SYS_TIME_H HAVE_UNISTD_H)
    endif()
    if(family STREQUAL sdhlt)
        target_compile_definitions(radbruter-${family} PRIVATE SDHLRAD)
    else()
        target_compile_definitions(radbruter-${family} PRIVATE HLRAD)
    endif()
    if(MSVC)
        target_compile_options(radbruter-${family} PRIVATE "$<$<NOT:$<CONFIG:Debug>>:/O2>" /fp:strict /W3 /FIclimits /FIcstdint /FIintrin.h)
    else()
        target_compile_options(radbruter-${family} PRIVATE -O2 -fno-strict-aliasing -ffp-contract=off "SHELL:-include climits" "SHELL:-include cstdint" -Wno-write-strings -Wno-register -Wno-deprecated-declarations)
    endif()
    target_link_libraries(radbruter-${family} PRIVATE lm_platform)
    add_dependencies(radbruter radbruter-${family})
endforeach()
