# Run the same executable without any optional GPU libraries, away from its source tree.
if(NOT EXISTS "${APP}")
    message(FATAL_ERROR "Invalid fallback test paths")
endif()
get_filename_component(app_name "${APP}" NAME)
get_filename_component(app_dir "${APP}" DIRECTORY)
if(HIDE_GPU)
    set(command "${CMAKE_COMMAND}" -E env CUDA_VISIBLE_DEVICES=-1 "${APP}")
    set(working_dir "${app_dir}")
else()
    file(REAL_PATH "${BUILD_ROOT}" test_root)
    cmake_path(ABSOLUTE_PATH STAGE NORMALIZE OUTPUT_VARIABLE stage_path)
    cmake_path(IS_PREFIX test_root "${stage_path}" NORMALIZE safe_stage)
    if(NOT IS_ABSOLUTE "${STAGE}" OR NOT safe_stage OR stage_path STREQUAL test_root)
        message(FATAL_ERROR "Fallback staging must stay inside the build directory")
    endif()
    file(MAKE_DIRECTORY "${STAGE}")
    file(REAL_PATH "${STAGE}" stage_path)
    cmake_path(IS_PREFIX test_root "${stage_path}" NORMALIZE safe_stage)
    if(NOT safe_stage OR stage_path STREQUAL test_root)
        message(FATAL_ERROR "Fallback staging resolves outside the build directory")
    endif()
    file(COPY "${APP}" DESTINATION "${STAGE}")
    file(COPY "${app_dir}/compilers" DESTINATION "${STAGE}")
    file(SHA256 "${APP}" original_hash)
    file(SHA256 "${STAGE}/${app_name}" copy_hash)
    if(NOT original_hash STREQUAL copy_hash)
        message(FATAL_ERROR "CPU fallback must use the same executable")
    endif()
    set(command "${STAGE}/${app_name}")
    set(working_dir "${STAGE}")
endif()
execute_process(COMMAND ${command} --help WORKING_DIRECTORY "${working_dir}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
if(NOT result EQUAL 0 OR error OR NOT output MATCHES "RadBruter")
    message(FATAL_ERROR "Standalone startup failed: ${result} ${error}")
endif()
execute_process(COMMAND ${command} --self-test WORKING_DIRECTORY "${working_dir}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 240)
if(NOT result EQUAL 0 OR error OR NOT output MATCHES "Automatic backend: cpu")
    message(FATAL_ERROR "Automatic CPU fallback failed: ${result}\n${output}\n${error}")
endif()
if(NOT HIDE_GPU)
    file(REAL_PATH "${STAGE}" cleanup_path)
    cmake_path(IS_PREFIX test_root "${cleanup_path}" NORMALIZE safe_cleanup)
    if(NOT safe_cleanup OR cleanup_path STREQUAL test_root OR NOT cleanup_path STREQUAL stage_path)
        message(FATAL_ERROR "Fallback cleanup path changed")
    endif()
    file(REMOVE_RECURSE "${cleanup_path}")
endif()
message(STATUS "Automatic CPU fallback passed with the unchanged executable")
